### ISSUE TITLE
How to ignore a property from being persisted

### ISSUE THREAD

**Issue by ajaishankar** [ServiceStack/PocoDynamo#7]
Is there a way to prevent a property from being persisted to DynamoDB? I have a couple of readonly properties, but they still get written to dynamo. Also in my CustomSession even when I do not have a [DataMember] attribute on a property it still gets serialized into CacheEntry item urn:iauthsession:***

**Comment by mythz** [comment]
It's unlikely read only properties were written to Dynamo as [they needed to be both readable + writable](https://github.com/ServiceStack/ServiceStack.Aws/blob/e1237b3262d25b5cc25e13ae83389fc1f0ea87b8/src/ServiceStack.Aws/DynamoDb/DynamoMetadata.cs#L151).

DynamoDB should follow the same behavior as OrmLite where `[Ignore]` attribute excludes fields from the DynamoDB table and `[IgnoreDataMember]` excludes fields from serialization, previously it was the other way around, (i.e. followed Text serializer instead of OrmLite behvaior), but I've just changed it back to follow [OrmLite in this commit](https://github.com/ServiceStack/ServiceStack.Aws/commit/af498f7e00672ba1fa34420e7a4cb7780e0e094a). This change is available from v4.0.61 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

Here's a [test showing the current behavior](https://github.com/ServiceStack/ServiceStack.Aws/blob/af498f7e00672ba1fa34420e7a4cb7780e0e094a/tests/ServiceStack.Aws.DynamoDbTests/PocoDynamoCreateTables.cs#L377).

**Comment by ajaishankar** [comment]
Looks like readonly properties of Nested objects are still persisted. Is this expected behavior? No biggie, just checking.

```
		public class Nested
		{
			public string Name { get { return "Foo"; } }
		}
		public class TableWithIgnoredFields
		{
			public TableWithIgnoredFields()
			{
				Nested = new Nested();
			}
			public Nested Nested { get; set; }
  		}
```

**Comment by mythz** [comment]
yeah that's the default behavior of complex type properties.
